name: wgpu_native
description: Experimental WGPU Dart bindings.
version: 0.0.0
homepage: https://github.com/jpnurmi/wgpu-native.dart
repository: https://github.com/jpnurmi/wgpu-native.dart
issue_tracker: https://github.com/jpnurmi/wgpu-native.dart/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  dylib: ^0.2.1-nullsafety.0
  ffi: ^0.2.0-nullsafety.1

dev_dependencies:
  ffigen: ^2.0.0-dev.2
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13
